FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY TodoList.Service/*.csproj ./TodoList.Service/
COPY TodoList.Service/nuget.config ./TodoList.Service/
COPY packages ./packages

WORKDIR /app/TodoList.Service
RUN dotnet restore --configfile nuget.config

COPY ./TodoList.Service .
RUN dotnet publish TodoList.Service.csproj -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/TodoList.Service/out ./

# Only required for debugging in vs code
RUN apt-get update \
  && apt-get install -y unzip curl \
  && mkdir -p /vsdbg \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
COPY .vsdbg /vsdbg
RUN chmod +x /vsdbg/vsdbg

EXPOSE 8080
EXPOSE 8443
EXPOSE 5005

ENTRYPOINT ["dotnet", "TodoList.Service.dll"]