version: '3.9'

services:
  identityservice:
    build:
      context: .
      dockerfile: Identity.Service/Dockerfile.debug
    ports:
      - "5001:5005" # debug


  todolistservice:
    build:
      context: .
      dockerfile: TodoList.Service/Dockerfile.debug
    ports:
     - "5002:5005" # debug

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - db
    networks:
      - backend