version: '3.9'

services:
  identityservice:
    build:
      context: .
      dockerfile: Identity.Service/Dockerfile
    ports:
      - "8081:8080" # http
      - "8444:8443" # https
      - "5001:5005" # debug
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE__Kestrel__Certificates__Default__Path
      - ASPNETCORE__Kestrel__Certificates__Default__Password
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Identity.Service
    depends_on:
      - db
    volumes:
      - ./logs/Identity.Service:/app/logs
    networks:
      - backend

  todolistservice:
    build:
      context: .
      dockerfile: TodoList.Service/Dockerfile
    ports:
     - "8080:8080" # http
     - "8443:8443" # https
     - "5002:5005" # debug
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE__Kestrel__Certificates__Default__Path
      - ASPNETCORE__Kestrel__Certificates__Default__Password
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__TodoList.Service
    depends_on:
      - db
      - identityservice
    volumes:
      - ./logs/TodoList.Service:/app/logs
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  todolistclient:
    build: ./TodoList.Client
    ports:
      - "4000:4000"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge