version: '3.9'

services:
  identityservice:
    build:
      context: .
      dockerfile: Identity.Service/Dockerfile
    ports:
      - "8081:8080"
    profiles:
      - backend
      - identity
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE__Kestrel__Certificates__Default__Path
      - ASPNETCORE__Kestrel__Certificates__Default__Password
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Identity.Service
    depends_on:
      - db
    volumes:
      - ./logs/Identity.Service:/app/logs
    networks:
      - backend

  todolistservice:
    build:
      context: .
      dockerfile: TodoList.Service/Dockerfile
    ports:
     - "8080:8080"
    profiles:
      - backend
      - todolist
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE__Kestrel__Certificates__Default__Path
      - ASPNETCORE__Kestrel__Certificates__Default__Password
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__TodoList.Service
    depends_on:
      - db
      - identityservice
    volumes:
      - ./logs/TodoList.Service:/app/logs
    networks:
      - backend

  todolistclient:
    build:
      context: .
      dockerfile: todolist-client/Dockerfile
    profiles:
      - frontend
    environment:
      - NODE_ENV
    ports:
      - "4000:4000"
    networks:
      - backend

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    profiles:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    profiles:
      - backend
      - db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    profiles:
      - tools
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  backend:
    driver: bridge