version: '3.9'

services:
  identityservice:
    build:
      context: .
      dockerfile: Identity.Service/Dockerfile.debug
    ports:
      - "5001:5005" # debug


  todolistservice:
    build:
      context: .
      dockerfile: TodoList.Service/Dockerfile.debug
    ports:
     - "5002:5005" # debug