version: '3.9'

services:
  todolistservice:
    build: ./TodoList.Service
    ports:
     - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TodoListDbConnection: "Host=db;Port=5432;Database=todolist;Username=postgres;Password=postgres"
    depends_on:
      - db
    networks:
      - backend
  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - backend
    
volumes:
  pgdata:

networks:
  backend:
    driver: bridge