version: '3.9'

services:
  identityservice:
    build: ./Identity.Service
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
    depends_on:
      - db
    networks:
      - backend

  todolistservice:
    build: ./TodoList.Service
    ports:
     - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__TodoListDbConnection
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
    depends_on:
      - db
      - identityservice
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge