FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY Identity.Service/*.csproj ./Identity.Service/
COPY Identity.Service/nuget.config ./Identity.Service/
COPY packages ./packages

WORKDIR /app/Identity.Service
RUN dotnet restore --configfile nuget.config

COPY ./Identity.Service .
RUN dotnet publish Identity.Service.csproj -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/Identity.Service/out ./

# Only required for debugging in vs code
RUN apt-get update \
  && apt-get install -y unzip curl \
  && mkdir -p /vsdbg \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
COPY .vsdbg /vsdbg
RUN chmod +x /vsdbg/vsdbg

EXPOSE 8080
EXPOSE 8443
EXPOSE 5005

ENTRYPOINT ["dotnet", "Identity.Service.dll"]