name: 🚀 Docker Compose Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .NET Dev Certificate
        run: |
          mkdir -p certs/https
          dotnet dev-certs https -ep certs/https/development.pfx -p "1111"

      - name: Generate Client Dev Certificate
        run: |
          mkdir -p TodoList.Client/certs
          openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
            -keyout TodoList.Client/certs/key.key \
            -out TodoList.Client/certs/cert.crt \
            -subj "/CN=localhost"

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Stop Docker Compose
        if: always()
        run: docker compose down