name: 🚀 Docker Compose Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Docker Compose
        run: |
          npm run docker:build
          npm run docker:fullstack:detach

      - name: Verify if services are running
        run: docker compose ps

      - name: Smoke tests
        run: |
          curl -k https://localhost || curl http://localhost || exit 1
          curl -k https://localhost/identity || curl http://localhost/identity || exit 1
          curl -k https://localhost/todolist || curl http://localhost/todolist || exit 1

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
