name: 🚀 Docker Compose Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Generate .NET Dev Certificate
        run: |
          npm run generate:certs

      - name: Run Docker Compose
        run: |
          npm run docker:build
          npm run docker:fullstack

      - name: Verify if services are running
        run: docker compose ps

      - name: Smoke test frontend
        run: curl -k http://localhost:4000 || exit 1

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
